language: java
sudo: false
jdk:
- oraclejdk8
install: true
before_install:
- test $TRAVIS_PULL_REQUEST = false && openssl aes-256-cbc -K $encrypted_45a1e02b23ba_key
  -iv $encrypted_45a1e02b23ba_iv -in gradle.properties.enc -out gradle.properties
  -d || true
script: "./gradle/buildViaTravis.sh"
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
notifications:
  slack:
    rooms:
     - secure: VCiBIEs9fA2ZVXZW/1TwhteNbylWVBsSAdGMMMdjh9oUjwFv6zUu+cNZK1RfY26cYfvhwuHr/l10yqM2hy0Z5an/+rSaQD8xdAs51K0H0kwmIDOXJVAX4XDg6Ep6GTcM8VAD8/7iOIHUqtmOIkC5C4sULw+dtbpauTWiKjHWZxp9RJJNa1RD1nfkF+IYKkxGN8lvllad/p46wcI87tPTRZLSGItYFu8ujmkHZ6RfHNDSFQ8Cuc0Fh8TxgBB+MsKPKQdc4b8I+AH1hQ7ew193OC+19d3kSRM0/1zlwK50EZe5rb7ry+aLs09DstN5HkpCuF7+fIbnhuiFjzyZ8D4afsYAEUUBn1nxkjzwX1iU8YWCVV7sH+dIlwWn44v4HOyUVpYw1AH1Yne5gdZxT/e8F8nWWh7aF3WEZ8bHP82c9PgoZrCh6AUeA51st+NWbZAZQb/lRDmvyFOJXccq4un9m8ZCcAZWhK7rQYdev9K8igdjgzsRkPgYi0DMeyKAHEyiMNcdLDxe8U40e94h+3tQzY8uW68/W9EahQPJYv4Y500rgYHEzVEuE7ctqv0d2spKwrd0A73OheToHT01G/SDQaypB4qbqH/smTHhp3NxZAXn8CQ2+XWXyzUj+0DCrq173qVMrW54JHNgu/gWLkRHn9A9gCgXCAQmYX1FP8rY8Dg=
    on_success: always
after_success:
- "./gradlew jacocoTestReport coveralls"
